name: Supabase Ping

# Keep the project active on Supabase's free tier.
# Supabase pauses projects after 7 days of inactivity.

on:
  schedule:
    # Runs every day at 4:00 AM UTC. This is well within the 7-day
    # inactivity window, ensuring the project remains active.
    - cron: '0 4 * * *'
  workflow_dispatch: # Allows manual triggering of the workflow for testing.

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase project URL
        env:
          # Get the Supabase URL and anon key from GitHub secrets
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          # Check if secrets are set
          if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
            echo "Error: SUPABASE_URL or SUPABASE_ANON_KEY secret not set."
            echo "Please add them to your repository settings."
            exit 1
          fi

          # Make an authenticated request to the Supabase API.
          response_code=$(curl -s -o /dev/null -w "%{http_code}" \
            --request GET \
            --url "${SUPABASE_URL}/rest/v1/" \
            --header "apikey: ${SUPABASE_ANON_KEY}" \
            --header "Authorization: Bearer ${SUPABASE_ANON_KEY}")

          # Check the HTTP response code
          if [[ "$response_code" -ge 200 && "$response_code" -lt 300 ]]; then
            echo "✅ Supabase ping successful! Response code: $response_code"
          else
            echo "❌ Supabase ping failed! Response code: $response_code"
            exit 1
          fi

